
version: "3.0"

networks:
  backend:
  local:
    driver: bridge

services:
  mongodb:
    image: 'mongo'
    container_name: 'mongo_proxy'
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    networks:
      - backend
  redis:
    image: 'redis:latest'
    container_name: 'redis_proxy'
    ports:
      - 6379:6379
    networks:
      - backend